### ISSUE TITLE
How about add CODE_OF_CONDUCT.md to Nanum?

### ISSUE THREAD

**Issue by bbvch13531** [LandvibeDev/Nanum#16]
## Expected Behavior
None.

## Actual Behavior
None.

## Steps to Reproduce the Problem
None.

## Specifications

  - Version:None.
  - Platform:None.
  - Subsystem:None.

## Type of issue
 - Doc

## Description
- I think opensource project should have code of conduct. 😄
How about add CODE_OF_CONDUCT.md to Nanum?
If this looks good on you, could I send PR that add CODE_OF_CONDUCT.md? 

I deliberately not follow issue template because this issue is not bug reporting. Sorry about that. 😢

**Comment by so3500** [comment]
Thank you for letting us improve on what we missed.
We welcome your PR!

We also changed the issue template to a more general form. (add Description, Type of Issue)
