### ISSUE TITLE
GPLv2 and MIT license compatibility

### ISSUE THREAD

**Issue by bbvch13531** [LandvibeDev/Nanum#18]
## Description
Nanum uses MySQL that follows [GPLv2](https://www.mysql.com/about/legal/licensing/oem/)license.
Nanum should not follows MIT license because MIT is not compatible to GPLv2.
Please check your license compatibility please.

## Type of Issue
  - [ ] bug report => please fill the templetes below.
  - [ ] feature request
  - [ X ] documentation (e.g. typo)
  
## Expected Behavior
None.

## Actual Behavior
None.

## Steps to Reproduce the Problem
None.

## Specifications
None.

**Comment by GuBeomJeong** [comment]
Thank you for your kind suggestion.
We will replace it with GPLv2.
Thank you again.
